export const site={
 name:'Kunduru Nagarjuna Reddy', email:'nagarjuna@gmail.com', mobile:'xxxxxxxxx', address:'164A, Kapra, Hyderabad, Telangana, India', location:'Kapra, Hyderabad, Telangana, India', qualifications:['UG Degree','MBA — Postgraduate'], positioning:'Tax & Government Permission Consultant',
 nav:[['Services','services'],['Permissions','permissions'],['Tax','tax'],['Property','property'],['Interiors','interiors'],['About','about'],['Contact','contact']] as const,
 images:{hero:'/images/hero/hero-architecture.jpg',profile:'/images/profile/kunduru-nagarjuna-reddy.jpg',property:['/images/property/property-villa.jpg','/images/property/property-apartment.jpg','/images/property/property-commercial.jpg'],interiors:['/images/interiors/interior-living.jpg','/images/interiors/interior-bedroom.jpg','/images/interiors/interior-kitchen.jpg','/images/interiors/interior-luxury.jpg','/images/interiors/interior-modern.jpg','/images/interiors/interior-minimal.jpg','/images/interiors/interior-renovation.jpg']}, social:{} as Record<string,string>,
 services:[
 {title:'Tax Services',items:['Tax filing assistance','Tax documentation support','Property tax estimation','Municipal tax estimation','House tax estimation','Shop/commercial tax estimation','Tax-related consultation','Property-related tax guidance']},
 {title:'Government Permission Assistance',items:['Building permission assistance','Property-related permission assistance','Municipal permissions','Shop/commercial permissions','Construction-related documentation','Renovation-related permission assistance','Municipal documentation','Applicable NOC/documentation assistance','Property documentation assistance','Water/sewerage related municipal application assistance where applicable','Layout/building-related approval process assistance where applicable','Trade/shop-related permission assistance where applicable'],note:'Assistance with the applicable government process. Final approval is subject to the relevant government authority and applicable rules.'},
 {title:'Property Services',items:['Property buying assistance','Property selling assistance','Property consultation','Property documentation support','Property tax estimation','Buyer/seller coordination','Property requirement analysis','Property-related government process assistance']},
 {title:'Interior Design',items:['House interior design','Living room design','Bedroom design','Kitchen design','Wardrobe design','Modern interiors','Luxury interiors','Minimal interiors','Space planning','Renovation concepts']}
 ],
 finder:[['I need tax assistance','Tax Services — Share your requirement and receive professional guidance.'],['I need a government permission','Government Permission Assistance — Tell us about your requirement and receive guidance on the applicable process.'],['I need property assistance','Property Services — Discuss the stage of your property requirement.'],['I want to buy property','Property Services — Explore your buying requirement with clarity.'],['I want to sell property','Property Services — Discuss your selling requirement and coordination needs.'],['I need property tax estimation','Tax Services — Receive indicative property tax guidance.'],['I need shop/commercial assistance','Government Permission Assistance — Discuss applicable process and documentation support.'],['I need interior design','Interior Design — Begin with your space, style and renovation concept.'],["I'm not sure",'Not sure where to begin? Let’s discuss the requirement and identify the right starting point.']],
 stages:[['Requirement','Clarify the requirement, the property and the location so the applicable process can be identified.'],['Documents','Identify and organize the documents that may be required for the applicable process.'],['Application','Prepare and present the applicable application through the relevant process.'],['Department','Understand which authority or department may be relevant to the requirement.'],['Verification','The applicable authority may review and verify the submitted requirement.'],['Approval','Final approval is subject to the relevant government authority and applicable rules.']],
 properties:[['Buy','A considered start for your property requirement.'],['Sell','Thoughtful coordination through your selling requirement.'],['Consult','Clearer perspective for property decisions.']],
 interiors:['Living','Bedroom','Kitchen','Luxury','Modern','Minimal','Renovation'],
 process:[['Discuss','Understand the requirement.'],['Document','Identify applicable documentation.'],['Coordinate','Assist with the applicable process.'],['Complete','Support the requirement through the applicable process.']],
 checklist:{Property:['Sale agreement draft','Title documents','Encumbrance certificate','Property tax records','Identity and address proof'],Building:['Site or layout details','Property ownership documents','Identity and address proof','Applicable drawings or plans','Previous records where applicable'],Shop:['Identity and address proof','Property occupancy or ownership record','Business-related details','Tax records where applicable','Applicable application details'],Tax:['Identity and address proof','Property or income-related records','Previous tax records where applicable','Supporting receipts or statements','Applicable registration details'],Renovation:['Property occupancy or ownership record','Existing plan or property details','Identity and address proof','Scope of renovation','Applicable permissions or records where applicable'],Other:['Identity and address proof','Requirement summary','Property or location details where applicable','Supporting documents','Applicable authority correspondence where available']},
 disclaimer:'Information provided on this website is for general guidance and professional assistance. Government permissions, taxes, approvals, fees and documentation requirements may vary depending on the applicable authority, location, property type, project and prevailing rules. Final decisions and approvals are made by the relevant government authorities. No approval or outcome is guaranteed.'
} as const;
